//
//  Constant.swift
//  omicallsdk
//
//  Created by LV on 12/12/2022.
//

import Foundation


let INIT_CALL = "INIT_CALL"
let UPDATE_TOKEN = "UPDATE_TOKEN"
let START_CALL = "START_CALL"
let END_CALL = "END_CALL"
let TOGGLE_MUTE = "TOGGLE_MUTE"
let TOGGLE_SPEAK = "TOGGLE_SPEAK"
let REGISTER = "REGISTER"
let SEND_DTMF = "SEND_DTMF"
let SWITCH_CAMERA = "SWITCH_CAMERA"
let CAMERA_STATUS = "CAMERA_STATUS"
let TOGGLE_VIDEO = "TOGGLE_VIDEO"
let INPUTS = "INPUTS"
let OUTPUTS = "OUTOUTS"
let SETINPUT = "SET_INPUT"
let SETOUTPUT = "SET_OUTPUT"

//LISTENER
let CALL_ESTABLISHED = "CALL_ESTABLISHED"
let CALL_END = "CALL_END"
let INCOMING_RECEIVED = "INCOMING_RECEIVED"
let CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
let SPEAKER = "SPEAKER"
let MUTED = "MUTED"


