//
//  Constant.swift
//  omicallsdk
//
//  Created by LV on 12/12/2022.
//

import Foundation

let START_SERVICES = "START_SERVICES"
let CONFIG_NOTIFICATION = "CONFIG_NOTIFICATION"
let INIT_CALL_API_KEY = "INIT_CALL_API_KEY"
let INIT_CALL_USER_PASSWORD = "INIT_CALL_USER_PASSWORD"
let GET_INITIAL_CALL = "GET_INITIAL_CALL"
let UPDATE_TOKEN = "UPDATE_TOKEN"
let START_CALL = "START_CALL"
let END_CALL = "END_CALL"
let TOGGLE_MUTE = "TOGGLE_MUTE"
let TOGGLE_SPEAK = "TOGGLE_SPEAK"
let REGISTER = "REGISTER"
let SEND_DTMF = "SEND_DTMF"
let SWITCH_CAMERA = "SWITCH_CAMERA"
let CAMERA_STATUS = "CAMERA_STATUS"
let TOGGLE_VIDEO = "TOGGLE_VIDEO"
let INPUTS = "INPUTS"
let OUTPUTS = "OUTOUTS"
let SET_INPUT = "SET_INPUT"
let SET_OUTPUT = "SET_OUTPUT"
let JOIN_CALL = "JOIN_CALL"
let START_CALL_WITH_UUID = "START_CALL_WITH_UUID"
let LOG_OUT = "LOG_OUT"
let REGISTER_VIDEO_EVENT = "REGISTER_VIDEO_EVENT"
let REMOVE_VIDEO_EVENT = "REMOVE_VIDEO_EVENT"
let GET_CURRENT_USER = "GET_CURRENT_USER"
let GET_GUEST_USER = "GET_GUEST_USER"

//LISTENER
let CALL_ESTABLISHED = "CALL_ESTABLISHED"
let CALL_END = "CALL_END"
let INCOMING_RECEIVED = "INCOMING_RECEIVED"
let VIDEO = "VIDEO"
let SPEAKER = "SPEAKER"
let MUTED = "MUTED"
let LOCAL_VIDEO_READY = "LOCAL_VIDEO_READY"
let REMOTE_VIDEO_READY = "REMOTE_VIDEO_READY"
let CLICK_MISSED_CALL = "CLICK_MISSED_CALL"


